# app specific settings
app:
  destination_queue: testq
  version: 0.3.0


# Spring boot - overriding settings
spring:
  activemq:
    broker-url: tcp://10.28.60.58:61616
    user: admin
    password: admin
    in-memory: true 
    pooled: false
  thymeleaf:
    cache: false
  profiles:
    active: development
  
#overriding embedded server properties
server:
  port: 8080
  context-path: /PlayPen



# application specific properties not overrides for spring boot opinions
#jenkins detail
jenkins:
  api:
     url: http://10.30.188.80:8777/jenkins/api/xml

#mas specific jenkins jobs
mas:
  jobs:
    prefix: MAS
   
ssl:
  port: 8443
---
#next yaml document
